from django.urls import path
from .views import *

urlpatterns = [
    path('Account/login/', ticket_login, name='login'),
    path('', dashboard, name='dashboard'),
    path('Tickets', index, name='tickets'),
    path('Tickets/create', ticket_create, name='tickets-create'),
    path('Tickets/<int:id>/details', ticket_details, name='tickets-details'),
    path('Tickets/<int:id>/edit', ticket_update, name='tickets-update'),
    path('Tickets/delete/<int:id>', ticket_delete, name='tickets-destroy'),
    # path('Change/mode',change_mode,name='change-mode'),
    path('Tickets/success/<int:id>', ticket_success, name='ticket_success'),
    path('Tickets/search-logs', search_logs, name='search_logs'),
    path('Tickets/Attachments/<int:id>/delete', ticket_attachment_delete, name='attachment_delete'),
    path('Tickets/Register', register, name='register'),
    path('Tickets/login', ticket_login, name='tickets-login'),
    path('Tickets/logout', ticket_logout, name='tickets-logout'),
    path('ticket/<int:ticket_id>/attachments/delete-all/', ticket_attachments_delete_all,
         name='ticket-attachments-delete-all'),
    path('ticket/<int:ticket_id>/attachments/download-all/', download_all_attachments,
         name='ticket-attachments-download-all'),
    path("assignee", assignee_ticket_list, name="assignee-list"),
    path("assignee/<int:id>", assignee_ticket_detail, name="assignee-detail"),
    path('assignee/<int:assignment_id>/mark-seen/', mark_assignment_seen, name='mark_assignment_seen'),
    path('ticket/<int:ticket_id>/seen-info/', get_ticket_seen_info, name='ticket_seen_info'),
    path('ticket/<int:ticket_id>/notes/', get_ticket_notes, name='ticket_notes'),
    path('ticket/<int:ticket_id>/notes/add/', add_ticket_note, name='add_ticket_note'),
    path('ticket/notes/<int:note_id>/edit/', edit_ticket_note, name='edit_ticket_note'),
    path('ticket/notes/<int:note_id>/delete/', delete_ticket_note, name='delete_ticket_note'),
    path('assignee/<int:id>', assignee_ticket_detail, name="assignee-detail"),
    path('assignee/ticket/<int:ticket_id>/notes/add/', add_ticket_note_assignee, name='add_ticket_note_assignee'),
    path('assignee/notes/<int:note_id>/edit/', edit_ticket_note_assignee, name='edit_ticket_note_assignee'),
    path('assignee/notes/<int:note_id>/delete/', delete_ticket_note_assignee, name='delete_ticket_note_assignee'),
    # URL های مربوط به یادداشت‌ها در صفحه جزئیات
    path('ticket/<int:ticket_id>/notes/add/details/', add_ticket_note_details, name='add_ticket_note_details'),
    path('ticket/notes/<int:note_id>/edit/details/', edit_ticket_note_details, name='edit_ticket_note_details'),
    path('ticket/notes/<int:note_id>/delete/details/', delete_ticket_note_details, name='delete_ticket_note_details'),
    path('ticket/<int:ticket_id>/mark-seen/', mark_ticket_seen, name='mark_ticket_seen'),
    path('ticket/<int:ticket_id>/seen-history/', get_seen_history, name='ticket_seen_history'),

]
