# Generated by Django 5.2.6 on 2025-09-14 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, help_text='The date the ticket was seen', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('solved', 'Solved'), ('impossible', 'Impossible')], default='new', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('assigned_ticket', models.ForeignKey(help_text='The ticket that will be assigned to this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments_tickets', to='Tickets.ticket')),
                ('assignee', models.ForeignKey(help_text='The user that will be assigned to this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'Tickets-Assignments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('assigned_ticket', 'assignee'), name='unique_ticket_assignee')],
            },
        ),
    ]
