# Generated by Django 5.2.6 on 2025-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
