# Generated by Django 5.2.6 on 2025-09-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_ticket_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
    ]
