# Generated by Django 5.2.6 on 2025-09-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='max_replay_date',
            field=models.DateTimeField(help_text='The maximum replay date the ticket will replay'),
        ),
    ]
