# Generated by Django 5.2.6 on 2025-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0006_alter_ticket_max_replay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='max_replay_date',
            field=models.DateTimeField(help_text='The maximum replay date the ticket will reply'),
        ),
    ]
