# Generated by Django 5.2.6 on 2025-10-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_ticket_actual_resolution_date_ticket_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='actual_resolution_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='estimated_resolution_date',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('', 'Select Department'), ('developer', 'Developer'), ('fullstack', 'Full Stack'), ('python', 'Python'), ('django', 'Django'), ('react', 'React')], default='Django', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('', 'Select Priority'), ('low', 'Low'), ('middle', 'Middle'), ('high', 'High'), ('secret', 'Secret')], default='Low', max_length=100),
        ),
    ]
