# Generated by Django 5.2.6 on 2025-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0010_alter_ticket_department_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('developer', 'Developer'), ('fullstack', 'Full Stack'), ('python', 'Python'), ('django', 'Django'), ('react', 'React')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High'), ('secret', 'Secret')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('solved', 'Solved'), ('impossible', 'Impossible')], max_length=20),
        ),
    ]
