# Generated by Django 5.2.7 on 2025-11-15 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0011_alter_ticket_department_alter_ticket_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('search_query', models.CharField(max_length=200)),
                ('priority', models.CharField(blank=True, max_length=100)),
                ('search_mode', models.CharField(default='and', max_length=10)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tickets.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SearchLog',
                'verbose_name_plural': 'SearchLogs',
                'db_table': 'Tickets-SearchLogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
