# Generated by Django 5.2.7 on 2025-11-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0012_searchlogsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, default='title_swiper', max_length=100, null=True)),
                ('name_swiper', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.FileField(blank=True, null=True, upload_to='swiper/')),
                ('name_of_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('description_swiper', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
