# Generated by Django 5.2.7 on 2025-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0013_swiper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Swiper',
        ),
        migrations.AddField(
            model_name='ticket',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High'), ('secret', 'Secret'), ('critical', 'Critical')], max_length=100),
        ),
    ]
