# Generated by Django 5.2.7 on 2025-12-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0016_swiper_searchlogsignal_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
    ]
